会場を株式会社インプレスに更新！！
Scotch-kilt/ichiyasaGitSample pull request #1
Opened 2023-12-05 13:34 UTC by Scotch-kilt

ホゲホゲ
わかりやすい文章とかなんとか。

2023-12-06 13:15 UTC, googugugugu commented
無問題。マージしる！！

2023-12-07 11:58 UTC, googugugugu requested changes
レビューしたでござる。
ただ会社名が微妙だったでござる。
ニンニン。

2023-12-07 11:58 UTC, googugugugu commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「株式会社インプレス〜ッ！」と正式名称を使用すべし。

2023-12-07 11:58 UTC, googugugugu commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「酢〜っ」？

2023-12-07 12:03 UTC, Scotch-kilt commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社インプレ酢〜っに修正します。

2023-12-07 12:04 UTC, googugugugu commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ヨシヨシ。

2023-12-07 12:06 UTC, googugugugu commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
😸

2023-12-07 12:08 UTC, googugugugu approved these changes

2023-12-07 12:37 UTC, merged